### PR TITLE
Fixed String method in Uint256

### LINKED ISSUE #207: DEV: Fix String method in Uint256
Align Uint256 String method as we do for Uint160. For more discussion read the following discussion: https://github.com/CityOfZion/neo-go/pull/183#discussion_r266254625

### PR DESCRIPTION
**Pull request by dauTT**
Closes #207

### CODE REVIEW

**Comment by decentralisedkev** [comment]
LGTM

**Comment by decentralisedkev** [comment]
To clarify the meaning of this PR, so that we do not need to search in other places. 

There is no internal switching of the endian being done, when we parse a string or when we DecodeBytes. If you want to switch the endian, you must explicitly do it with the Reverse method as shown by Dautt

**Comment by hal0x2328** [comment]
Award dauTT 100 points

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/d5ae4a22ffe49912a2a3dc698d39ac63a8fcf2cef63ae136850d039c312591d8

**Pull request merged**
