### PR TITLE
Fix #140 (improve error messages)

### LINKED ISSUE #140: improve error message
As requested by @kim, the error message must follow this convention:
 
`{"jsonrpc":"2.0","error":{"code":-2146233033,"message":"One of the identified items was in an invalid format."},"id":1}`

To find more about the context of this issue read [here](https://github.com/CityOfZion/neo-go/pull/135#discussion_r257521065)

**TODO**: refactor the errors methods in the  [errors.go](https://github.com/CityOfZion/neo-go/blob/master/pkg/rpc/errors.go) file accordingly and amends all tests.

### PR DESCRIPTION
**Pull request by im-kulikov**
- return errors like in C# code (neo-project/neo#587)
- update tests
- small refactoring

### CODE REVIEW

**Comment by im-kulikov** [comment]
@decentralisedkev / @fabwa any thoughts?

**Comment by im-kulikov** [comment]
> I have noticed, that `assert.Equal` is used for comparing json's. `assert.JSONEq` seems more suitable here to me. Could you change it?

I think it would be better to do it in a separate PR, don't you think?

**Comment by im-kulikov** [comment]
I add issue for your proposal https://github.com/CityOfZion/neo-go/issues/155

**Comment by hal0x2328** [comment]
Award im-kulikov 150 points
Award fyrchik 30 points for review

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/144dc06fbc54dd84165af08ddd9c01e8a720ca1bb05471dfd1af1503160f245f

**Pull request merged**
