### PR TITLE
Added rpc unit tests

### PR DESCRIPTION
**Pull request by dauTT**
### Problem

Added rpc unit tests

### Solution
We have created unit tests based on a blockchain fixture which is generated by running the [neo-python-privnet-unittest](https://hub.docker.com/r/cityofzion/neo-python-privnet-unittest/) image. The unit tests have been tested manually and by running the command:

```
go test ./...
```

### Notes
Currently the chain fixture are store in the path `cli/chains/unit_testnet folder`. This is a temporary location. In future we will need to create a fixture folder where we can store the blockchain/notifactions fixture, testing wallets and anything useful for running the unit tests.

Use [semver](https://semver.org/) to bump `VERSION`, and remember to run the following after
merging your PR:

```
make push-tag
```

### CODE REVIEW

**Comment by dauTT** [comment]
@anthdm ,
Could you cross check why the tests are failing on github? If you run them locally they will pass.

**Comment by anthdm** [comment]
@dauTT checking it out right now.

**Comment by dauTT** [comment]
@anthdm ,
any update on this PR? Let me know if you need my help.

(FYI, the next rpc call `GetAccountStatus` is implemented but I won't create a new PR unless this one is fixed and merged.)

**Comment by anthdm** [comment]
@dauTT Tests are still failing, can you have look to fix them?

**Comment by hal0x2328** [comment]
Please reward dauTT 300 points.

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/144dc06fbc54dd84165af08ddd9c01e8a720ca1bb05471dfd1af1503160f245f

**Pull request merged**
