### PR TITLE
Setup TravisCI for dev branch

### LINKED ISSUE #157: Setup CI/CD
https://circleci.com/ or https://travis-ci.org/ are known solutions. However any will do.

### PR DESCRIPTION
**Pull request by im-kulikov**
fix #157

before merge, needs #160 to be merged

Just need enable TravisCI, who has write access for this repo

---

cc @decentralisedkev

### CODE REVIEW

**Comment by decentralisedkev** [comment]
I don't have the access to do this, I'll contact someone. Leaving it open as a reminder

**Comment by im-kulikov** [comment]
@fabwa @anthdm can you help us?

**Comment by im-kulikov** [comment]
https://travis-ci.com/im-kulikov/neo-go/builds/102359590

I test on my repo.. works fine.. 

we needs to correct golint's notes and the tests will be done successfully

**Comment by fabwa** [comment]
@decentralisedkev with great power comes great responsibility

**Pull request merged**
