### PR TITLE
Fix CircleCI

### PR DESCRIPTION
**Pull request by im-kulikov**
just for test circle-ci

### CODE REVIEW

**Comment by im-kulikov** [comment]
@decentralisedkev https://circleci.com/workflow-run/bda7e1fa-cf00-4cab-a6ea-f9f3de15bff2

try to run CI on this PR

**Comment by im-kulikov** [comment]
this PR just for demonstrate, that CircleCI works fine

**Comment by decentralisedkev** [comment]
Check this one too: https://circleci.com/gh/CityOfZion/neo-go

**Comment by im-kulikov** [comment]
seems like CI not enabled for all branches

**Comment by im-kulikov** [comment]
close this PR after enabling CI

**Comment by decentralisedkev** [comment]
CircleCI was not working, however we got the permissions needed for Travis. Thank you for making both of the files needed!

**Pull request closed without merging**
