### PR TITLE
Simplify code and improve performance (crypto/PublicKey.DecodeBinary)

### PR DESCRIPTION
**Pull request by im-kulikov**
- optimize crypto/PublicKey.DecodeBinary
- add new method crypto/PublicKey.DecodeBytes

### CODE REVIEW

**Comment by hal0x2328** [comment]
Please reward im-kulikov 200 points.

**Comment by im-kulikov** [comment]
m?

**Comment by hal0x2328** [comment]
> m?

This is part of the new system for CoZ awards for PRs. When the award is paid out there should be a TXID attached to the thread (although going forward it will be tracked on on a prior issue that has been tagged for low/medium/high impact that was solved by the PR, rather than the PR itself)

**Comment by lllwvlvwlll** [comment]
@im-kulikov please provide a neo address to award.

**Comment by im-kulikov** [comment]
@lllwvlvwlll AcraNnCuPKnUYtPYyrACRCVJhLpvskbfhu

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/f40fecc31e4164aada19b2315c47af968a9f6ce6a9425b94576c5a4fb8878ce2

**Pull request merged**
